#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject.Forms
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SportsData")]
	public partial class WNBADataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public WNBADataClassesDataContext() : 
				base(global::GroupProject.Properties.Settings.Default.SportsDataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WNBADataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WNBADataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WNBADataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WNBADataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WNBA> WNBAs
		{
			get
			{
				return this.GetTable<WNBA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WNBA")]
	public partial class WNBA
	{
		
		private string _Player_Name;
		
		private System.Nullable<double> _GP;
		
		private System.Nullable<double> _GS;
		
		private System.Nullable<double> _MIN;
		
		private System.Nullable<double> _PTS;
		
		private System.Nullable<double> _OR;
		
		private System.Nullable<double> _DR;
		
		private System.Nullable<double> _REB;
		
		private System.Nullable<double> _AST;
		
		private System.Nullable<double> _STL;
		
		private System.Nullable<double> _BLK;
		
		private System.Nullable<double> _TO;
		
		private System.Nullable<double> _PF;
		
		private System.Nullable<double> _AST_TO;
		
		private System.Nullable<double> _FGM;
		
		private System.Nullable<double> _FGA;
		
		private System.Nullable<double> _FG_;
		
		private System.Nullable<double> @__3PM;
		
		private System.Nullable<double> @__3PA;
		
		private System.Nullable<double> @__3P_;
		
		private System.Nullable<double> _FTM;
		
		private System.Nullable<double> _FTA;
		
		private System.Nullable<double> _FT_;
		
		private string _Position;
		
		private string _Team_Name;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
		public WNBA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Player Name]", Storage="_Player_Name", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Player_Name
		{
			get
			{
				return this._Player_Name;
			}
			set
			{
				if ((this._Player_Name != value))
				{
					this._Player_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this._GP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GS", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> GS
		{
			get
			{
				return this._GS;
			}
			set
			{
				if ((this._GS != value))
				{
					this._GS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIN", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> MIN
		{
			get
			{
				return this._MIN;
			}
			set
			{
				if ((this._MIN != value))
				{
					this._MIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTS", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> PTS
		{
			get
			{
				return this._PTS;
			}
			set
			{
				if ((this._PTS != value))
				{
					this._PTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[OR]", Storage="_OR", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> OR
		{
			get
			{
				return this._OR;
			}
			set
			{
				if ((this._OR != value))
				{
					this._OR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> DR
		{
			get
			{
				return this._DR;
			}
			set
			{
				if ((this._DR != value))
				{
					this._DR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REB", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> REB
		{
			get
			{
				return this._REB;
			}
			set
			{
				if ((this._REB != value))
				{
					this._REB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AST", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> AST
		{
			get
			{
				return this._AST;
			}
			set
			{
				if ((this._AST != value))
				{
					this._AST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STL", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> STL
		{
			get
			{
				return this._STL;
			}
			set
			{
				if ((this._STL != value))
				{
					this._STL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLK", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> BLK
		{
			get
			{
				return this._BLK;
			}
			set
			{
				if ((this._BLK != value))
				{
					this._BLK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TO]", Storage="_TO", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> TO
		{
			get
			{
				return this._TO;
			}
			set
			{
				if ((this._TO != value))
				{
					this._TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PF", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> PF
		{
			get
			{
				return this._PF;
			}
			set
			{
				if ((this._PF != value))
				{
					this._PF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[AST/TO]", Storage="_AST_TO", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> AST_TO
		{
			get
			{
				return this._AST_TO;
			}
			set
			{
				if ((this._AST_TO != value))
				{
					this._AST_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FGM", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> FGM
		{
			get
			{
				return this._FGM;
			}
			set
			{
				if ((this._FGM != value))
				{
					this._FGM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FGA", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> FGA
		{
			get
			{
				return this._FGA;
			}
			set
			{
				if ((this._FGA != value))
				{
					this._FGA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FG%]", Storage="_FG_", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> FG_
		{
			get
			{
				return this._FG_;
			}
			set
			{
				if ((this._FG_ != value))
				{
					this._FG_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3PM]", Storage="__3PM", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> _3PM
		{
			get
			{
				return this.@__3PM;
			}
			set
			{
				if ((this.@__3PM != value))
				{
					this.@__3PM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3PA]", Storage="__3PA", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> _3PA
		{
			get
			{
				return this.@__3PA;
			}
			set
			{
				if ((this.@__3PA != value))
				{
					this.@__3PA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3P%]", Storage="__3P_", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> _3P_
		{
			get
			{
				return this.@__3P_;
			}
			set
			{
				if ((this.@__3P_ != value))
				{
					this.@__3P_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTM", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> FTM
		{
			get
			{
				return this._FTM;
			}
			set
			{
				if ((this._FTM != value))
				{
					this._FTM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTA", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> FTA
		{
			get
			{
				return this._FTA;
			}
			set
			{
				if ((this._FTA != value))
				{
					this._FTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FT%]", Storage="_FT_", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> FT_
		{
			get
			{
				return this._FT_;
			}
			set
			{
				if ((this._FT_ != value))
				{
					this._FT_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Team Name]", Storage="_Team_Name", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Team_Name
		{
			get
			{
				return this._Team_Name;
			}
			set
			{
				if ((this._Team_Name != value))
				{
					this._Team_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this._SSMA_TimeStamp = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
