#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject.Forms
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SportsData")]
	public partial class BaseballDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BaseballDataClassesDataContext() : 
				base(global::GroupProject.Properties.Settings.Default.SportsDataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaseballDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseballDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseballDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseballDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Baseball> Baseballs
		{
			get
			{
				return this.GetTable<Baseball>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Baseball")]
	public partial class Baseball
	{
		
		private string _Player_Name;
		
		private string _Position;
		
		private System.Nullable<double> _GP;
		
		private System.Nullable<double> _AB;
		
		private System.Nullable<double> _R;
		
		private System.Nullable<double> _H;
		
		private System.Nullable<double> @__2B;
		
		private System.Nullable<double> @__3B;
		
		private System.Nullable<double> _HR;
		
		private System.Nullable<double> _RBI;
		
		private System.Nullable<double> _TB;
		
		private System.Nullable<double> _BB;
		
		private System.Nullable<double> _SO;
		
		private System.Nullable<double> _SB;
		
		private System.Nullable<double> _AVG;
		
		private System.Nullable<double> _OBP;
		
		private System.Nullable<double> _SLG;
		
		private System.Nullable<double> _OPS;
		
		private System.Nullable<double> _WAR;
		
		private string _Team_Name;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
		public Baseball()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Player Name]", Storage="_Player_Name", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Player_Name
		{
			get
			{
				return this._Player_Name;
			}
			set
			{
				if ((this._Player_Name != value))
				{
					this._Player_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this._GP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AB", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> AB
		{
			get
			{
				return this._AB;
			}
			set
			{
				if ((this._AB != value))
				{
					this._AB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> H
		{
			get
			{
				return this._H;
			}
			set
			{
				if ((this._H != value))
				{
					this._H = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2B]", Storage="__2B", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> _2B
		{
			get
			{
				return this.@__2B;
			}
			set
			{
				if ((this.@__2B != value))
				{
					this.@__2B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3B]", Storage="__3B", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> _3B
		{
			get
			{
				return this.@__3B;
			}
			set
			{
				if ((this.@__3B != value))
				{
					this.@__3B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HR", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> HR
		{
			get
			{
				return this._HR;
			}
			set
			{
				if ((this._HR != value))
				{
					this._HR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RBI", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> RBI
		{
			get
			{
				return this._RBI;
			}
			set
			{
				if ((this._RBI != value))
				{
					this._RBI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> TB
		{
			get
			{
				return this._TB;
			}
			set
			{
				if ((this._TB != value))
				{
					this._TB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BB", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> BB
		{
			get
			{
				return this._BB;
			}
			set
			{
				if ((this._BB != value))
				{
					this._BB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> SO
		{
			get
			{
				return this._SO;
			}
			set
			{
				if ((this._SO != value))
				{
					this._SO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SB", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> SB
		{
			get
			{
				return this._SB;
			}
			set
			{
				if ((this._SB != value))
				{
					this._SB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVG", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> AVG
		{
			get
			{
				return this._AVG;
			}
			set
			{
				if ((this._AVG != value))
				{
					this._AVG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBP", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> OBP
		{
			get
			{
				return this._OBP;
			}
			set
			{
				if ((this._OBP != value))
				{
					this._OBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLG", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> SLG
		{
			get
			{
				return this._SLG;
			}
			set
			{
				if ((this._SLG != value))
				{
					this._SLG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPS", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> OPS
		{
			get
			{
				return this._OPS;
			}
			set
			{
				if ((this._OPS != value))
				{
					this._OPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAR", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> WAR
		{
			get
			{
				return this._WAR;
			}
			set
			{
				if ((this._WAR != value))
				{
					this._WAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Team Name]", Storage="_Team_Name", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Team_Name
		{
			get
			{
				return this._Team_Name;
			}
			set
			{
				if ((this._Team_Name != value))
				{
					this._Team_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this._SSMA_TimeStamp = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
